### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Roycegao** [AMEERAZAM08/sam-sdxl-inpainting#1]
Hello, I followed the installation steps,

Git clone

CD

Pip install - r requirements. txt

An error occurred while executing the Python app. py. What is the problem?
My operating environment is: 8-core 32GB graphics memory 24GB, ubuntu22.04 cuda121.0 py310 torch2.1.2-tf2.14.0-1.11.0

![image](https://github.com/AMEERAZAM08/sam-sdxl-inpainting/assets/25998119/27130ac2-3050-48eb-a291-f04b53d727a5)
![image](https://github.com/AMEERAZAM08/sam-sdxl-inpainting/assets/25998119/f09df387-0ef8-406a-a536-777863ada1f5)

**Comment by AMEERAZAM08** [comment]
Can you look into colab if possible @yigediaosi

**Comment by Roycegao** [comment]
Thank you for your reply! I am using a modelscope that is similar to a colab.
